/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import com.formdev.flatlaf.FlatLightLaf;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormatter;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.LocalDateTime;
import org.joda.time.Duration;



/**
 *
 * @author lenov
 */
public class ToDoList extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToDoList.class.getName());

    /**
     * Creates new form ToDoList
     */
    public ToDoList() {
        initComponents();
        generate();
        new javax.swing.Timer(60000, e ->{
            DateTimeFormatter format = DateTimeFormat.forPattern("yyyy-MM-dd hh:mm a");
            DateTime  rn = DateTime.now();
            List<DataItem> data = crjava.readData();
            for(DataItem dataItem : data){
                Duration deadline = new Duration(rn, format.parseDateTime(dataItem.waktu));
                if(deadline.getStandardMinutes() <= 5 && deadline.getStandardMinutes() <=0 ){
                    Panelnotif notif = new Panelnotif();
                    notif.pro(dataItem.id, dataItem.nama, dataItem.waktu, dataItem.status, dataItem.deskripsi);
                }
            }
        });
    }

    public void generate() {
        List<DataItem> todoList = crjava.readData();
        for (DataItem dataItems : todoList) {
            Card card = new Card(dataItems.nama, dataItems.deskripsi, dataItems.status, dataItems.waktu);
            PList.add(card);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        AddTodo.setBackground(new java.awt.Color(0, 204, 51));
        AddTodo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        AddTodo.setForeground(new java.awt.Color(255, 255, 255));
        AddTodo.setText("+");
        AddTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        PList.setToolTipText("");
        PList.setAutoscrolls(true);
        PList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PList.setLayout(new java.awt.GridLayout(0, 1, 8, 8));
        jScrollPane1.setViewportView(PList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTodoActionPerformed
        // TODO add your handling code here:
        ControlToDo control = new ControlToDo(); // kirim referensi form utama
        control.setVisible(true);
    }//GEN-LAST:event_AddTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            // Aktifkan tema FlatLaf
            FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Gagal memuat FlatLaf: " + ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            //ToDoList() di ghanti sesuai nama form
            new ToDoList().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTodo;
    public javax.swing.JPanel PList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
